### ISSUE TITLE
Doen't work anymore?

### ISSUE THREAD

**Issue by Fr3d-P** [nateg5/Android#1]
Hello, 
This solution (Install Chromium with Widevine), like the simlar one from kust8 isn't working anymore?
When I thied those, just Chromium didn't lauch at all it crashes just
Rapsberry Pi 3 B+ Raspbian GNU/Linux 9

**Comment by nateg5** [comment]
> Hello,
> This solution (Install Chromium with Widevine), like the simlar one from kust8 isn't working anymore?
> When I thied those, just Chromium didn't lauch at all it crashes just
> Rapsberry Pi 3 B+ Raspbian GNU/Linux 9

Hmm, it is still working on mine. Give this a try if you haven't already.

sudo apt-get remove chromium-browser
sudo apt-get update
sudo apt-get dist-upgrade

Then search for any left over chromium related directories and manually delete those. Of course be careful when manually deleting directories.

sudo find / | grep -i chromium
sudo rm -rf &lt;path to the directory you want to delete&gt;

Then try following the instructions again to setup Chromium and Widevine.

**Comment by Fr3d-P** [comment]
Hello, thanks for your answer. This worked!
The last time I tried, It was just after a clean install with Noobs. I tried kust8's solution, then reinstalled Chromium and then tried this method. 
So it should be the installation from Noobs or the version of kust8 that left something that blocked the software.
Thanks again
